### ISSUE TITLE
Project overview - Worskspaces list

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#122]
**Specifications**
-  Wireframes:  https://extranet.who.int/confluence/x/OQHiB

**In Scope**
- Project overview page, as per specifications
- Project settings tab allows user to make changes to existing project
- Create project button allows user to create a new project
- Workspaces tab shows the list of workspaces for the project, as per specifications

**Out of Scope**
- Other tabs will be implemented by additional stories
- User permissions still need to view redesigned.  For the time being all features (list, create, ...) will be available to all users

**Comment by vivekjain197** [comment]
@matof-who I have pushed on git Cristian will review and merge

**Comment by matof-who** [comment]
Remaining fixes

- [ ]  As for the situation updates, when creating a new facility (Register new facility button) the following fields should be stored in the responses table: response_type, survey_date, status, created_at, created_by, latest_update_date, latest_update_by

**Comment by vivekjain197** [comment]
Latest update column should be renamed to "Latest survey" an should show the most recent survey date (for both admin and situation responses)
**ME:- I have fixed**

After creating/editing a workspace, user should be redirected to the workspace list again
**ME:- Already working after finish default timeout of message display**

**Comment by matof-who** [comment]
Sorry, I did not see before, the ID column is missing, can you please add ?

**Comment by vivekjain197** [comment]
I have added ID

**Comment by matof-who** [comment]
@vivekjain197 
I think it has the wrong column type, the filter appears with a calendar for dates



![Image](https://github.com/HeRAMS-WHO/herams-backlog/assets/70581697/0b7c4251-efd3-43ba-842d-a7695f539fd3)

**Comment by vivekjain197** [comment]
I have fixed now as well

**Comment by matof-who** [comment]
@vivekjain197 ID works fine now
However, the "Delete workspace" option in the workspaces settings tab does not appear to work
Can you take a look ? Sorry, I discover new things as I test
