### ISSUE TITLE
List of open access requests not accessible

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backlog#123]
**Describe the bug**

https://herams.org/access-request/index is not accessible (time-out error)

**Steps to Reproduce**
1. From the world map click access requests
2. In the notification tab, click the eye icon

**Comment by matof-who** [comment]
@luna404 
Can you please confirm if it's working fine now and close ?

**Comment by luna404** [comment]
It's working fine. Before closing the issue could just let me know what the timeframe is? Did you say 60 or 90 days?

**Comment by cristiangirlea** [comment]
@luna404 currently its -90days, we can change that.
