### ISSUE TITLE
Change banner color for Staging and Staging v2

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#147]
To avoid confusions when making tests. Can we change the banner color for Staging environments ?

For staging V1

![Image](https://user-images.githubusercontent.com/70581697/229823598-643f29d3-a6a5-45d7-9732-cdc1412e3b2e.png)

For staging V2

![Image](https://user-images.githubusercontent.com/70581697/229823818-c7c9c739-926f-42aa-af14-d8178411ed04.png)

**Comment by vivekjain197** [comment]
@matof-who as I discussed before, I have change color of header green on staging V2 please check and let me know if you anything else color.

**Comment by matof-who** [comment]
Done for V2
