### ISSUE TITLE
Weblate instance is down

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#152]
Since the last Kubernetes upgrade, Weblate is down (https://weblate.herams-staging.org/)

![Image](https://user-images.githubusercontent.com/70581697/230382623-d55be0d4-676e-4c15-a152-0a56ff123e50.png)

The related pod in Kubernetes was not able to start

**Comment by cristiangirlea** [comment]
This is due permissions 


![Image](https://user-images.githubusercontent.com/26361024/230443216-44050f85-950f-4d8d-96a4-bbc0822286d1.png)

**Comment by cristiangirlea** [comment]
![image](https://user-images.githubusercontent.com/26361024/230473008-f749023d-ea24-4399-860b-bd1579c3cec6.png)
this looks like I have missing environment variable

**Comment by cristiangirlea** [comment]
weblate is now working.
Issue, missing extension "btree_gin" from postgres, note to add the extension you need to be logged in as a superuser.
environment variables for postgress login no longer working. I need to make new secrets for the those.

**Comment by matof-who** [comment]
From Cristian: 

> by the way I fixed the Weblate, but there are more things to 2:
> 
> next time we upgrade make sure that the required driver gets installed on postgress (first issue)
> 
>  I need to put secrets for the postgress sql, because the current one no longer work, If there is a mail service in that client I need to check it because it may not work, the credentials seems to be from there, so I manually added them to t he k8s, I need to make secrets for them.
> 
> the driver is installed like this:
> 
> kubectl exec -it postgres-0 -n staging -- psql -U postgresadmin weblate
> CREATE EXTENSION btree_gin
