### ISSUE TITLE
WS sync not working as expected

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backlog#162]
**Describe the bug**
We're having an issue with the sync between the LS and HeRMAS DBs. Currently, users update data in the LS DB. Whenever they submit a record this record should be inserted into the HeRAMS DB. As we sometimes do edits through the backend interface in LS and as we've had past issues with this, we have the ability to force sync workspaces to ensure HeRMAS is in line with LS. 

It appears that something is not working properly anymore with the sync function and we can't insert new records. 

**Steps to Reproduce**
1. Try this link: https://herams.org/workspace/12685/refresh  (you might not have permissions for it)

**Expected behavior**
Error message: 
``SQLSTATE[HY000]: General error: 1442 Can't update table 'prime2_response' in stored function/trigger because it is already used by statement which invoked this stored function/trigger. The SQL being executed was: INSERT INTO `prime2_response` (`id`, `workspace_id`, `survey_id`, `date`, `hf_id`, `data`, `last_updated`) VALUES (12595, 12685, 666685, '2023-04-25', '2106qJ', CAST('{\"BACC1\":\"A3\",\"BACC1x\":{\"1\":\"A4\"},\"BACO1\":\"A1\",\"BACO2\":{\"1\":\"A2\"},\"BAEN1\":\"A1\",\"BAEN2\":{\"1\":\"A1\"},\"BAFC1\":\"A3\",\"BAFC1x\":{\"1\":\"A6\",\"2\":\"A4\"},\"BAHA1\":\"A3\",\"BAHA1x\":{\"1\":\"A4\"},\"BAINP1\":{\"SQ001\":\"A4\",\"SQ002\":\"A4\",\"SQ003\":\"A4\"},\"BASA1\":\"A3\",\"BASA1x\":{\"1\":\"A4\"},\"BAWA1\":\"A1\",\"BAWA2\":{\"1\":\"A4\"},\"BAWM1\":\"A1\",\"BAWM2\":\"A1\",\"BAWM3\":\"A1\",\"BAWM4\":{\"1\":\"A7\"},\"CONDB\":\"A1\",\"CONDE\":\"A1\",\"GEO1\":\"D0606\",\"GEO5\":\"A1\",\"GEO6\":\"Adiga Zanguina\",\"HFACC\":\"A1\",\"HFCONTACT\":{\"FUNCT\":\"ASC\",\"NAME\":\"Inoussa Bako\",\"PHONE\":\"97236452\"},\"HFFUNCT\":\"A1\",\"HFSUP1\":\"A3\",\"INFO1\":\"A1\",\"INFO2\":\"A1\",\"INFO3\":\"A1\",\"MoSD2\":\"Adiga Zanguina\",\"MoSD3\":\"A14\",\"MoSD4\":\"A1\",\"MoSD5\":\"A1\",\"MoSD6\":\"Adiga zanguina\",\"MoSD7\":\"A1\",\"MoSDGPS\":{\"SQ001\":\"12.28360650\",\"SQ002\":\"3.30781170\"},\"MoSDPOP\":\"1611.0000000000\",\"QHeRAMS100\":\"A4\",\"QHeRAMS101\":\"A4\",\"QHeRAMS102\":\"A4\",\"QHeRAMS103\":\"A4\",\"QHeRAMS104\":\"A4\",\"QHeRAMS106\":\"A4\",\"QHeRAMS107\":\"A1\",\"QHeRAMS110\":\"A4\",\"QHeRAMS112\":\"A4\",\"QHeRAMS113\":\"A4\",\"QHeRAMS117\":\"A4\",\"QHeRAMS122\":\"A4\",\"QHeRAMS123\":\"A4\",\"QHeRAMS124\":\"A4\",\"QHeRAMS125\":\"A4\",\"QHeRAMS126\":\"A4\",\"QHeRAMS127\":\"A4\",\"QHeRAMS200\":\"A4\",\"QHeRAMS201\":\"A1\",\"QHeRAMS202\":\"A1\",\"QHeRAMS204\":\"A1\",\"QHeRAMS205\":\"A1\",\"QHeRAMS206\":\"A4\",\"QHeRAMS207\":\"A1\",\"QHeRAMS208\":\"A1\",\"QHeRAMS209\":\"A4\",\"QHeRAMS210\":\"A4\",\"QHeRAMS301\":\"A4\",\"QHeRAMS302\":\"A4\",\"QHeRAMS303\":\"A1\",\"QHeRAMS304\":\"A1\",\"QHeRAMS305\":\"A4\",\"QHeRAMS306\":\"A1\",\"QHeRAMS307\":\"A1\",\"QHeRAMS308\":\"A4\",\"QHeRAMS309\":\"A4\",\"QHeRAMS310\":\"A4\",\"QHeRAMS411\":\"A1\",\"QHeRAMS412\":\"A4\",\"QHeRAMS413\":\"A4\",\"QHeRAMS414\":\"A4\",\"QHeRAMS415\":\"A4\",\"QHeRAMS416\":\"A4\",\"QHeRAMS417\":\"A4\",\"QHeRAMS421\":\"A1\",\"QHeRAMS422\":\"A4\",\"QHeRAMS423\":\"A4\",\"QHeRAMS424\":\"A4\",\"QHeRAMS425\":\"A4\",\"QHeRAMS427\":\"A4\",\"QHeRAMS428\":\"A4\",\"QHeRAMS431\":\"A4\",\"QHeRAMS432\":\"A4\",\"QHeRAMS433\":\"A4\",\"QHeRAMS501\":\"A4\",\"QHeRAMS502\":\"A4\",\"QHeRAMS503\":\"A4\",\"QHeRAMS504\":\"A4\",\"QHeRAMS505\":\"A4\",\"QHeRAMS507\":\"A4\",\"QHeRAMS508\":\"A4\",\"QHeRAMS509\":\"A4\",\"QHeRAMS510\":\"A4\",\"QHeRAMS511\":\"A4\"}' AS JSON), '2023-05-01 07:06:56')``

**Current behavior**
Because of the sync issue, we don't have all records in the HeRAMS DB, meaning they don't appear on the dashboards, exports, etc. 

**Screenshots**
Here's a picture of the extend of the issue for a single project. 
[If applicable, add screenshots to help explain your problem.](https://herams.org/project/70/sync-workspaces)
![image](https://user-images.githubusercontent.com/18245059/235420477-97793116-a45c-4a44-82be-939b09065cce.png)

**Comment by matof-who** [comment]
Hi @luna404 
One trigger was created by mistake in the prod DB, we have removed it
Can you please test again if the sync works ?

**Comment by luna404** [comment]
Thanks for the swift reaction, the insert seems to be working again. 

I still have some issues with duplicates, which might just be the result of people not syncing workspaces properly on our side. As these issues are rather hard to resolve on my side, can you force sync all projects on your end?

**Comment by luna404** [comment]
resolved
