### ISSUE TITLE
Hosting & license overview / budget

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backlog#24]
@matof-who is budgeting for hosting & licenses also part of your job description / skill set? Now that we're working towards having a structure in place where we can pay for these things might be good to get some insights into what we're spending and where we're spending it?

Current: DO hosting
Todo:
- DO hosting
- SurveyJS license [mandatory] https://surveyjs.io/pricing
- AgGrid Premium license [optional] https://www.ag-grid.com/license-pricing

**Comment by matof-who** [comment]
Yes, it is part of my job : )
And I will need to calculate all the licence recurring cost for the next year. Would you have some time to review the figures with me ? I think we will need to add also those two: 

- SendGRID
- Confluence

**Comment by SamMousa** [comment]
Sendgrid is free for our usage. If it increases the lower tiers are still quite cheap: https://sendgrid.com/pricing/

Honestly I'm not sold on Confluence yet. For example if you look at the requirements analysis process for the export:
- You create your document in Confluence because that is a tool you are familiar with.
- You post a link in the GitHub issue
- We have no Notifications if the document changes, as there's no link between Confluence and Github.

I feel for the part where group communication is required Confluence is not the right tool, or more specifically: doesn't offer the right level of integration with Github. That said I do not know of another tool that makes it as easy to use the different visual editors like Confluence does.
For the document part I feel a github wiki is fine (and you can even just use a local editor for it that syncs to the wiki repo).  That still leaves us with things like integrating wireframes..

**Comment by SamMousa** [comment]
No, @matof-who will unplug it when the new one is added.

**Comment by SamMousa** [comment]
Ah, it is for the $19.95 monthly subscription. I can't provide a billing user here so @matof-who when you get to it I'll need to give you access to my account for updating the billing information.
I've removed your account Samuel, and added one for Fatima so she can update the billing info asap.

**Comment by SamuelPetragallo** [comment]
Ok - so keeping my cc in until we have resolved

**Comment by matof-who** [comment]
Licences costing forecast documented in Confluence: https://extranet.who.int/confluence/x/GIB9B
