### ISSUE TITLE
Workspace overview - Health Facilities list

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#32]
**Specifications**
- Wireframe: https://extranet.who.int/confluence/x/RgHiB

**In Scope**
- Workspace overview page, as per specifications
- Workspace settings tab allows user to make changes to existing workspace
- Create workspace button allows user to create a new project
- Health Facilities tab shows the list of HF for the project, as per specifications. 

**Out of Scope**
- Update situation button in the Health Facility list will be implemented by additional stories
-   Other tabs will be implemented by additional stories
- User permissions still need to view redesigned. For the time being all features (list, create, ...) will be available to all users

**Comment by matof-who** [comment]
Remaining fixes

- [ ] As for the situation updates, when creating a new facility (Register new facility button) the following fields should be stored in the responses table: response_type, survey_date, status, created_at, created_by, latest_update_date, latest_update_by

**Comment by matof-who** [comment]
Hi @vivekjain197 
None of the issues described in the previous comments seem to be fixed in Stating V2
Can you please check if the deployment is correct ?

**Comment by vivekjain197** [comment]
As for the situation updates, when creating a new facility (Register new facility button) the following fields should be stored in the responses table: response_type, survey_date, status, created_at, created_by, latest_update_date, latest_update_by
**ME:- I need to discuss about this point from your question not getting**

"Latest survey" data column is missing, and should show the most recent survey date (for both admin and situation responses)
**ME:- I this functionality already working.**

After creating a new health facility, user should be redirected to the health facilities list again
**ME:- It is also redirect to list after some time once finished default timeout**
