### ISSUE TITLE
List health facilities responses (situation update)

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#41]
**Specifications**
Wireframe: https://extranet.who.int/confluence/x/TwHiB

**In Scope**
- List of situation updates, as per specifications
- Update situation buttons allows user to create a new situation response
- Action buttons are enabled for all users and perform the defined action (view, edit, delete)

**Out of scope**
- Creation and edition of drafts will be included in an additional story. For the time being all responses are saved with "Validated" status
- User permissions still need to view redesigned. For the time being all features (list, create, ...) will be available to all users

**Comment by matof-who** [comment]
A couple of things to fix:

- The survey_data is not updated correctly, it takes the date of the previous survey (instead of the current survey)
- created_date and last_update_data should be stored in CET timezone

**Comment by matof-who** [comment]
Hi @vivekjain197 , can you please take a look at the remaining issue concerning the columns display, They should appear by default as in the wireframe

**Comment by vivekjain197** [comment]
@matof-who, As I checked in AgGrid library, there is  not any option to make default order of any column, we need to arrange atlest one time. May be we can close this ticket.

**Comment by matof-who** [comment]
@vivekjain197 have you checked the method setColumnState() for grid. 
https://www.ag-grid.com/angular-data-grid/column-updating-definitions/#maintain-column-order

My last project was using AG Grid also, and we could define the default column order

**Comment by luna404** [comment]
Question, where do the values for the answer option come from? This does neither correspond to the answer code nore the label. 
![image](https://github.com/HeRAMS-WHO/herams-backlog/assets/18245059/d585f2d6-337d-4874-9327-c7081230f0e4)

Also as a default can we please sort the list of updates by date of update in descending order?

**Comment by matof-who** [comment]
Hi @luna404 
- concerning the values in the table, these responses where created before I've renamed the fields with the new encoding. So surveyJS does not know what is the correct value and it's showing the data as it was saved at the time. To test properly,  you can create a new Health facility an enter new data, it should show correcty
- For the sorting, I've added this comment already to this ticket: https://github.com/HeRAMS-WHO/herams-backlog/issues/138#issuecomment-1576413850, so you can ignore for this one
- For the filter and the date picker, I will open a separate issue
