### ISSUE TITLE
List health facilities responses (admin update)

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#42]
**Specifications**
Wireframe: https://extranet.who.int/confluence/x/DoATBQ

**In Scope**

- List of admin updates, as per specifications
- Update health facility button allows user to create a new adminresponse
- Action buttons are enabled for all users and perform the defined action (view, edit, delete)

**Out of scope**

- Creation and edition of drafts will be included in an additional story. For the time being all responses are saved with "Validated" status
- User permissions still need to view redesigned. For the time being all features (list, create, ...) will be available to all users

**Comment by matof-who** [comment]
Remaining fixes

- [ ] After adding a new response, user should be redirected to the admin responses list again

**Comment by matof-who** [comment]
HIi @vivekjain197 , can you please take a look at the remaining issues in the previous comment. some of the are still not working in Staging

**Comment by luna404** [comment]
Field order does not always respect the order defined in the questionnaire. If you add a new field to the table it's always added as the last field. 
For example, I've added "HSDU Name" as shown below.
![image](https://github.com/HeRAMS-WHO/herams-backlog/assets/18245059/8fca28e3-1d85-4182-8bfd-cf66a35a2e20)

In the table it added it added it as the last column. 
![image](https://github.com/HeRAMS-WHO/herams-backlog/assets/18245059/8778fcce-b0b5-4088-867b-98da66d3b6ce)

**Comment by matof-who** [comment]
Hi @luna404 
The component we use for grids remembers the last column configuration from the last visit of the user, so if the user changes manually the column order next time he will same the same order

This has a  side effect that if you add a new columns to be visible in the survey, it will appear last unless it's the first time you visit the page. However, you can reset the column  configuration to the default by clicking the button "Reset grid" on the top right of the table

I that ok for you ? Maybe we can force a reset of the user last configuration each time, we would need to investigate this
