### ISSUE TITLE
Add additional items to the dashboard page title drop-down list

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#55]
**Steps to reproduce**

- Open any project admin page and go to the "Dashboard settings" tab
- Click on the "Create page" button
- Click on the first field "Title"  to see the predefined options

**Current situation**
Only the following options are available

![Image](https://user-images.githubusercontent.com/70581697/206512194-b87aa434-3b55-483a-9172-eb76d4089dab.png)

**Requirement**

We need to add the following pre-defined options, so they can be translated to ukranian 

- Hand Hygiene
- Communications
- Cleaning equipment
- Heating
- Transportation
- Connectivity
- Support

![Image](https://user-images.githubusercontent.com/70581697/206512910-57d6bfd1-6207-40d1-a606-e51819b63164.png)

**Comment by matof-who** [comment]
Hi @SamMousa 
Do you think this change can be done before next monday ? We have a demo in Ukraine and we would like to show the dashboard including those titles translated to Ukrainian

**Comment by SamMousa** [comment]
Cant you just type in a custom name?

**Comment by matof-who** [comment]
Yep, but then it cannot be automatically translated to other languages
We need to have these pages in english and ukrainian

**Comment by SamMousa** [comment]
Sure, but lets not make this more urgent than it needs to be. This project has been running for weeks and this could have been easily foreseen.

When I add these languages they will need to be translated in weblate before they can become part or a release.

In any case, no reason to rush it. Just put the title in English and add Ukrainian between ( ) for the demo.

**Comment by breakhard** [comment]
> Sure, but lets not make this more urgent than it needs to be. This project has been running for weeks and this could have been easily foreseen.
> 
> When I add these languages they will need to be translated in weblate before they can become part of a release.
> 
> In any case, no reason to rush it. Just put the title in English and add Ukrainian between ( ) for the demo.

Hi @SamMousa , indeed, we thought about adding them translated into the title but it seems it is not working in UKR (I guess encoding issue?).

**Comment by matof-who** [comment]
Hi @SamMousa 
Can you please advise when this can be done, and if there's any risk on moving it to production quickly ?

**Comment by matof-who** [comment]
Hi @SamMousa 

If my understanding is good this is a minor change with no regression risks for other projects (please correct me if I'm wrong), and it needs to be done anyway for the UKR project.  

Please make the change today, we can discuss tomorrow during the weekly on how to prevent urgent releases in the future.

**Comment by SamMousa** [comment]
> If my understanding is good this is a minor change with no regression risks for other projects (please correct me if I'm wrong), and it needs to be done anyway for the UKR project.

There is no regression risk code-wise, but there is always risk that comes with a release. We do not have zero-downtime releases and there is no out-of-office hours for doing a release. Has there been any discussion with other project owners?
I'm pretty sure @breakhard himself won't be happy if I deployed a release in the midst of his demo today...

**Comment by SamMousa** [comment]
The workaround works so I'm leaving this for tomorrow's discussion.

**Comment by luna404** [comment]
If I understood correctly, the workaround is not working given the encoding issue.

As you said yourself @SamMousa there is a low risk that adding the additional items to the drop-down list and releasing the translations will break anything. As we don't have anything scheduled for this afternoon, I'm willing to take the chance. 

I generally agree with you that this is not good practice, but given that's a very low-risk quick fix for something that has high visibility, I think we should make an exception and implement the changes.

**Comment by SamMousa** [comment]
> If I understood correctly, the workaround is not working given the encoding issue.

No, this part you misunderstood. The encoding issue was an easier fixed that already has been implemented and confirmed to be working by @breakhard.

**Comment by SamMousa** [comment]
@breakhard is there a reason for "Hand Hygiene" being capitalized? It's inconsistent with existing titles in the platform as well as other titles in the ticket.

**Comment by breakhard** [comment]
@SamMousa , Hand Hygiene is part of the basic amenities part and that's currently the way it is presented in the questionnaire.  @luna404 is it ok for you?

**Comment by SamMousa** [comment]
That doesn't answer my question. Other titles do not capitalize the second word, for example: Cleaning **e**quipment. 

To me it seems like a mistake to capitalize the word *Hygiene*. Seems to have some origins in German language capitalizing all nouns.

Looking at the current 33 titles, 23 consist of multiple words. Out of those 23 only 3 use this capitalization.

**Comment by breakhard** [comment]
> That doesn't answer my question. Other titles do not capitalize the second word, for example: Cleaning **e**quipment.
> 
> To me it seems like a mistake to capitalize the word _Hygiene_. Seems to have some origins in German language capitalizing all nouns.
> 
> Looking at the current 33 titles, 23 consist of multiple words. Out of those 23 only 3 use this capitalization.

Ok, sorry i didn't undestand your question. Indeed you can change it to "Hand hygiene"

**Comment by SamMousa** [comment]
You can translate them in weblate. Please put a note here when that's done.

**Comment by SamMousa** [comment]
When this workflow finishes: https://github.com/HeRAMS-WHO/herams-backend/actions/runs/3704520159

It should be available for testing in the staging environment.

**Comment by breakhard** [comment]
Thank you!
