### ISSUE TITLE
Rename button "Add a new response" into  "Add an update"

### ISSUE THREAD

**Issue by breakhard** [HeRAMS-WHO/herams-backlog#79]
**Requirements**
Despite reinforcing the training on the difference between edition (using pencil) and addition of a new response (make an update), and despite the warning notification of the risks of overwritting a response, users are still confused when working on the platform and keep editing instead of adding a new response. 
**Proposed solution**
Instead of reading "add a new response" it can be more straightforward to have the "Add an update" label for the blue button to add a new response when updating the questionnaire.
**Acceptance criteria**
Any other confirmation notification is still relevant to highlight the difference between the 2 commands: 

- Editing using the pencil button : "You are in process of overwriting an existing response. You should only proceed if you wish to complete a draft response or to correct a data entry error. To update the questionnaire, please select "Cancel" and click the blue "**add an update**" button"

**Additional context**

**Comment by luna404** [comment]
@matof-who can we quickly discuss this during the next sprint planning? 

As this is related to the response picker, is it possible to change the label without requiring a full release? 

@breakhard the pop-up messages are controlled in the survey settings https://ls.herams.org/admin/survey/sa/editsurveysettings/surveyid/322125#pluginsettings . On the bottom of the page you have two fields where you can define the pop-up message (update = edit, repeat = add response/update). The only issue we're having is that this message can only be configured in one language.

**Comment by cristiangirlea** [comment]
Changed the label to Add an update.

**Comment by cristiangirlea** [comment]
@luna404 this is fixed in #92
