### ISSUE TITLE
Review form for  project create / update

### ISSUE THREAD

**Issue by matof-who** [HeRAMS-WHO/herams-backlog#82]
Add fields:

- [x] Latitude (mandatory)
- [x] Longitude (mandatory)
- [x] Overrides: replace by a field with a link for custom dashboard (optional)

Update field
- [x] Country: add a "(training)" country, make mandatory

Not needed anymore
- [x] Typemap
- [x] Status

**Comment by SamMousa** [comment]
All implemented. 

- [ ] Test on preview branch

**Comment by luna404** [comment]
We're missing the `Visibility` field 
![image](https://user-images.githubusercontent.com/18245059/222380377-709e1d2d-e3d6-4f02-82b7-310af9e8e8ec.png)

**Comment by SamMousa** [comment]
Form is defined here `protected/models/forms/createUpdateProject.json`.
The API model is located here `microservices/api/src/domain/project/NewProject.php`.
Documentation might be in the `docs/` folder.

Ask me questions here or on discord!

**Comment by matof-who** [comment]
Hi @vivekjain197 
As discussed this morning during the review, can we change the order of fields in the "create project" form ?
Latitude should appear just before Longitude (right now Longitude appear befor)

**Comment by cristiangirlea** [comment]
it is not necessary, I already did that, is not merged.
