### ISSUE TITLE
`herams-staging.org` domain

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backlog#89]
The `herams.org` is registered to @SamuelPetragallo using his account on 101domain.com.

Please confirm that you will be able to move the domain `herams-staging.org` if I send you the transfer code in a private channel.

**Comment by SamMousa** [comment]
Alternatively we should check if there is a better way to have these registrations on non-personal accounts. @matof-who

**Comment by matof-who** [comment]
Domaine transferred
