### ISSUE TITLE
Sendgrid account

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backlog#90]
We cannot have more than 2 people in the team with our current account.
Since our billing provider at argusoft is in the team this means that I cannot invite anyone else.

My proposal:
1. Remove argusoft as billing manager
2. Add @matof-who as owner
3. Remove @SamMousa as owner
4. Add argusoft as billing manager

**Comment by SamMousa** [comment]
Invited @matof-who as admin.

**Comment by matof-who** [comment]
Hi @SamMousa 
I have access to SendGrid but you are still the admin, so I cannot add/remove team mates


![Image](https://user-images.githubusercontent.com/70581697/223126197-d14597ed-81df-4738-a9a1-df1d5d3c6f15.png)

**Comment by SamMousa** [comment]
All transferred.
