### ISSUE TITLE
Add missing translations to response picker

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backlog#92]
**Requirements**
Translations for some of the labels in the response picker are hard-coded and cannot be updated on our side. These missing translations are causing issues with users not understanding the difference between editing and adding a new response. 

**Proposed solution**
We need to add translations for Ukranian and Portuguese for the fields highlighted below. 
![image](https://user-images.githubusercontent.com/18245059/222760799-32282400-5b41-48fe-aa78-398d5fdd11fc.png)

**Acceptance criteria**
Response picker must display correctly in the 5 major language used (English, French, Arabic, Portuguese and Ukrainian)

**Additional context**
Issue is related #79

**Comment by matof-who** [comment]
Hi @SamMousa 
This is a high priority issue, can you please make the assessment ?
![image](https://user-images.githubusercontent.com/70581697/223115393-830992fe-660b-41e3-8164-f587e828eae5.png)

**Comment by SamMousa** [comment]
This is the content that is currently translatable. 
https://github.com/HeRAMS-WHO/ls-responsepicker/blob/master/ResponsePicker.php#L397
```php
        {
            $this->translation['en']['No text found for'] = 'No text found for';
            $this->translation['fr']['No text found for'] = 'Pas de donnée pour';
            $this->translation['ar']['No text found for'] = 'لم يتم ايجاد نص ل';
            $this->translation['en']['Add a new response'] = 'Add a new response';
            $this->translation['fr']['Add a new response'] = 'Ajouter une réponse';
            $this->translation['ar']['Add a new response'] = 'اضف إجابة';
            $this->translation['en']['Response id'] = 'Response id';
            $this->translation['fr']['Response id'] = 'ID de la réponse';
            $this->translation['ar']['Response id'] = 'رقم الاستجابة';
            $this->translation['en']['Date of update'] = 'Date of update';
            $this->translation['fr']['Date of update'] = 'Date de mise à jour';
            $this->translation['ar']['Date of update'] = 'تاريخ تحديث الإستبيان';
            $this->translation['en']['Actions'] = 'Actions';
            $this->translation['fr']['Actions'] = 'Actions';
            $this->translation['ar']['Actions'] = 'إجراءات';
        }
````


Adding new translations is relatively simple.
For the green `new` tag we'll need some extra work.

- [ ] Unarchive the responsepicker repo
- [ ] Add new translation values to code
- [ ] Fix CSS hardcoded string to use translation in PHP

Should take < 3 hours. Post the translations here please!

**Comment by luna404** [comment]
Yes, please go ahead with it.

**Comment by matof-who** [comment]
@luna404 Can you please add the translations to start the implementat

**Comment by luna404** [comment]
I'm still waiting for confirmation from our focal points for the two translations in italic. I'll update this as soon as I have confirmation from them. 

|     English (base language)    |     French              |     Arabic                |     Portuguese                                           |     Ukrainian                |
|--------------------------------|-------------------------|---------------------------|----------------------------------------------------------|------------------------------|
|     Response ID                |     Id de la réponse    |     رقم   التحديث         |     Codigo de resposta                                   |     ID відповіді             |
|     Actions                    |     Actions             |     اجراءات               |     Acções                                               |     Дії                      |
|     New                        | Nouvelle                |     جديد                  |     Novo                                                 |     Нова                     |
|     Add an update              | Ajouter une mise à jour |     إضافة   تحديث جديد    |     _Acrescentar uma nova resposta_                        |     _Додати нову відповідь_    |

**Comment by SamMousa** [comment]
Portugese is `pt`, Ukrainian is `ua`.

**Comment by cristiangirlea** [comment]
Hello, I made a pull request. Please note that there are missing translations for the following:
"No text found for"
"Date of update"
Also should "Response id" change to "Update id"?

**Comment by breakhard** [comment]
> Hello, I made a pull request. Please note that there are missing translations for the following: "No text found for" "Date of update" Also should "Response id" change to "Update id"?
hi Cristian, I think indeed it would be great to have those translated too!

**Comment by luna404** [comment]
@cristiangirlea I'll provide you the missing translations shortly. 

I have a question regarding the term "date of update". Doesn't this come from the survey itself? It's one of the questions in the survey and I thought it was taken from there as we do for the remaining headers.

**Comment by cristiangirlea** [comment]
@luna404 I'm not sure, those are the current translations, there are other texts that are in English in that functionality, but only the ones from above and the ones you provided were translated. 
So currently those are the current ones:
```
        {
            $this->translation['en']['No text found for'] = 'No text found for';
            $this->translation['fr']['No text found for'] = 'Pas de donnée pour';
            $this->translation['ar']['No text found for'] = 'لم يتم ايجاد نص ل';
            $this->translation['en']['Add an update'] = 'Add an update';
            $this->translation['fr']['Add an update'] = 'Ajouter une mise à jour';
            $this->translation['ar']['Add an update'] = 'إضافة تحديث جديد';
            $this->translation['pt']['Add an update'] = 'Acrescentar uma nova resposta';
            $this->translation['uk']['Add an update'] = 'Додати нову відповідь';
            $this->translation['en']['Response id'] = 'Response id';
            $this->translation['fr']['Response id'] = 'ID de la réponse';
            $this->translation['ar']['Response id'] = 'رقم الاستجابة';
            $this->translation['pt']['Response id'] = 'Codigo de resposta';
            $this->translation['uk']['Response id'] = 'ID відповіді';
            $this->translation['en']['Date of update'] = 'Date of update';
            $this->translation['fr']['Date of update'] = 'Date de mise à jour';
            $this->translation['ar']['Date of update'] = 'تاريخ تحديث الإستبيان';
            $this->translation['en']['Actions'] = 'Actions';
            $this->translation['fr']['Actions'] = 'Actions';
            $this->translation['ar']['Actions'] = 'إجراءات';
            $this->translation['pt']['Actions'] = 'Acções';
            $this->translation['uk']['Actions'] = 'Дії';
            $this->translation['en']['New'] = 'New';
            $this->translation['fr']['New'] = 'Nouveau';
            $this->translation['ar']['New'] = 'جديد';
            $this->translation['pt']['New'] = 'Novo';
            $this->translation['uk']['New'] = 'Нова';
        }
```
As you can see there is no translation for 'No text found for' and also 'Date of update'.

**Comment by luna404** [comment]
It's still strange that the date of update is included in the strings there as normally you should be able to get it from the questionnaire as we do it for the other variables. But not important, we're not gonna fix what is not broken... 


Here are the updated translations. 
| English (base language) 	| French 	| Arabic 	| Portuguese 	| Ukrainian 	|
|---	|---	|---	|---	|---	|
| Update ID 	| Id de la réponse 	| رقم التحديث 	| Codigo de resposta 	| ID відповіді 	|
| Actions 	| Actions 	| اجراءات 	| Acções 	| Дії 	|
| New 	| Nouveau 	| جديد 	| Novo 	| Нова 	|
| Add an update 	| Ajouter une mise à jour 	| إضافة تحديث جديد 	| Acrescentar uma nova resposta 	| Додати оновлення 	|
| No text data found for 	| Pas de donnée pour 	| لم يتم ايجاد نص ل 	| Sem dados para 	| Немає даних 	|
| Date of update 	| Date de mise à jour 	| تاريخ تحديث الإستبيان 	| Data de actualização 	| Дата оновлення 	|
| # of updates 	| # de mises à jour 	|  	| # de resposta 	| # оновлень 	|

The one missing for Arabic will follow shortly. 

I've added one more field `# of responses` which is the first column header and which does not seem to be included in the list of variable that needs to be translated. I don't know if it's easy to add another word to the above list but if possible could we add this as well so the entire table translates properly. 
![image](https://user-images.githubusercontent.com/18245059/224268618-912fe324-3166-4e88-8f80-dc5135b89f91.png)

**Comment by luna404** [comment]
For got to add, can we change the English label for "no text found for" to "no data found for"?

**Comment by luna404** [comment]
Arabic translations have been updated in the above table.

**Comment by cristiangirlea** [comment]
yes the change can change from "no text found for" to "no data found for", Please give also translation for "# of response"

**Comment by cristiangirlea** [comment]
made the latest changes.

**Comment by cristiangirlea** [comment]
@luna404 Changes where added, it can be tested now.

**Comment by luna404** [comment]
@cristiangirlea you seem to have reverted the layout back to the LS default, meaning responses are no longer grouped by HFs. As this change is already visible can you revert this back until you had a chance to look at it with @SamMousa? 

![image](https://user-images.githubusercontent.com/18245059/224709089-d251c8bc-46b4-4699-8fb3-7b9b19fec3da.png)

You can test your results here but be aware that you are modifying a live view. 
https://ls.herams.org/survey/index/sid/457826/token/pbrGd1_neUx_cVz/lang//newtest/Y

**Comment by cristiangirlea** [comment]
@luna404 I reverted it back

**Comment by cristiangirlea** [comment]
@luna404 Please let me know if it's working now.
